In [2]:
import torch
b=3
t=4
vocab_size=5
logits = torch.randn((b, t, vocab_size))
# print(logits)
input_ids = torch.randint(low=0, high=vocab_size, size=(b, t))
print(input_ids)
# Get the probabilities using softmax
probs = torch.softmax(logits, dim=-1)
print(probs)
# Flatten the probabilities and input_ids tensors
probs = probs.view(b*t, -1)
input_ids = input_ids.view(b*t)

# Get the probabilities for the input_ids
input_probs = torch.gather(probs, dim=1, index=input_ids.unsqueeze(1))

# Reshape the probabilities tensor to match the shape of input_ids
input_probs = input_probs.view(b, t)

print(input_probs.shape)  # (b, t)
print(input_probs)


tensor([[4, 3, 0, 4],
        [3, 3, 4, 1],
        [3, 2, 1, 0]])
tensor([[[0.1337, 0.3494, 0.0254, 0.3228, 0.1687],
         [0.0668, 0.2152, 0.2133, 0.4478, 0.0569],
         [0.1909, 0.0941, 0.1236, 0.3587, 0.2328],
         [0.5949, 0.0463, 0.1171, 0.0431, 0.1986]],

        [[0.2478, 0.6146, 0.0830, 0.0219, 0.0328],
         [0.5875, 0.1575, 0.0884, 0.0212, 0.1455],
         [0.3837, 0.0377, 0.1511, 0.3245, 0.1031],
         [0.1429, 0.4570, 0.0215, 0.3211, 0.0575]],

        [[0.1262, 0.0491, 0.0708, 0.1700, 0.5838],
         [0.0908, 0.2909, 0.1474, 0.4296, 0.0413],
         [0.0511, 0.3814, 0.2524, 0.0658, 0.2492],
         [0.1168, 0.5151, 0.1010, 0.1983, 0.0689]]])
torch.Size([3, 4])
tensor([[0.1687, 0.4478, 0.1909, 0.1986],
        [0.0219, 0.0212, 0.1031, 0.4570],
        [0.1700, 0.1474, 0.3814, 0.1168]])


In [1]:
for i in range(100):
    print(i)
    i = i + 4
    print(i)

0
4
1
5
2
6
3
7
4
8
5
9
6
10
7
11
8
12
9
13
10
14
11
15
12
16
13
17
14
18
15
19
16
20
17
21
18
22
19
23
20
24
21
25
22
26
23
27
24
28
25
29
26
30
27
31
28
32
29
33
30
34
31
35
32
36
33
37
34
38
35
39
36
40
37
41
38
42
39
43
40
44
41
45
42
46
43
47
44
48
45
49
46
50
47
51
48
52
49
53
50
54
51
55
52
56
53
57
54
58
55
59
56
60
57
61
58
62
59
63
60
64
61
65
62
66
63
67
64
68
65
69
66
70
67
71
68
72
69
73
70
74
71
75
72
76
73
77
74
78
75
79
76
80
77
81
78
82
79
83
80
84
81
85
82
86
83
87
84
88
85
89
86
90
87
91
88
92
89
93
90
94
91
95
92
96
93
97
94
98
95
99
96
100
97
101
98
102
99
103
