In [20]:
import torch
logits = torch.tensor([[5,4,3,2,1],[2,4,1,3,5],[1,2,3,4,5]])
labels = torch.tensor([4,-100,3])
active_loss_position = (labels != -100).nonzero().squeeze()
active_loss_position = (labels != -100)
top_k = 2
top_k_preds = torch.topk(logits, k=top_k, dim=-1).indices
top_k_correct = torch.eq(top_k_preds, labels.unsqueeze(-1)).any(dim=-1).float().sum()
top_k_acc = top_k_correct / active_loss_position.size(0)
preds = torch.argmax(logits, dim=-1)
acc = (preds[active_loss_position] == labels[active_loss_position]).float().mean()  #这个True False的tensor可以直接作为index


In [18]:
print(labels.unsqueeze(-1))

tensor([[   4],
        [-100],
        [   3]])


In [15]:
print(preds[active_loss_position])

tensor([0, 4])


In [14]:
print(preds)
print(acc)

tensor([0, 4, 4])
tensor(0.)


In [11]:
print(active_loss_position)

tensor([ True, False,  True])


In [9]:
print(top_k_preds)

tensor([[0, 1],
        [4, 1],
        [4, 3]])


In [19]:
print(top_k_acc)

tensor(0.5000)


In [2]:
a = [1,2]
import torch
a = torch.tensor(a,dtype=torch.float32)

In [3]:
print(a)

tensor(1.5000)


In [10]:
a = [1]
a = torch.tensor(a,dtype=torch.float32)

In [11]:
print(torch.tensor(a,dtype=torch.float32))

tensor([1.])


/tmp/ipykernel_3896031/2571157480.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  print(torch.tensor(a,dtype=torch.float32))


In [8]:
print(a.shape)

torch.Size([])


In [9]:
print(a.item())

1.0


In [1]:
a = [1.3]
print(float(a))

TypeError: float() argument must be a string or a number, not 'list'

In [6]:
import torch
c = [torch.tensor([1.5,1.6],dtype=torch.float),torch.tensor([1.5,1.6],dtype=torch.float)]

# print(torch.tensor(c))
print(torch.cat(c))
print(torch.stack(c).flatten())

tensor([1.5000, 1.6000, 1.5000, 1.6000])
tensor([1.5000, 1.6000, 1.5000, 1.6000])


In [4]:
import torch
d = [torch.tensor(1.6,dtype=torch.float),torch.tensor(1.6,dtype=torch.float)]


# print(torch.cat(d)) # 报错zero-dimensional tensor (at position 0) cannot be concatenated

print(torch.stack(d))

tensor([1.6000, 1.6000])


In [9]:
import torch 
f = torch.tensor([1],dtype=torch.float32)
print(f)
print(f.shape)
e = torch.tensor(1,dtype=torch.float32)
print(e)
print(e.shape)

tensor([1.])
torch.Size([1])
tensor(1.)
torch.Size([])


In [8]:
import torch
from transformers import get_linear_schedule_with_warmup,get_cosine_schedule_with_warmup
from torch.optim import AdamW

network = torch.nn.Linear(100,100)
Adam = AdamW(network.parameters(),lr = 0.1)
schedule = get_cosine_schedule_with_warmup(Adam,num_warmup_steps=1,num_training_steps=5)

In [9]:
print(Adam.param_groups[0]['lr'])
schedule.step()
print(Adam.param_groups[0]['lr'])
schedule.step()
print(Adam.param_groups[0]['lr'])
schedule.step()
print(Adam.param_groups[0]['lr'])
schedule.step()
print(Adam.param_groups[0]['lr'])
schedule.step()
print(Adam.param_groups[0]['lr'])
schedule.step()

0.0
0.1
0.08535533905932738
0.05
0.014644660940672627
0.0
