In [20]:
import torch
logits = torch.tensor([[5,4,3,2,1],[2,4,1,3,5],[1,2,3,4,5]])
labels = torch.tensor([4,-100,3])
active_loss_position = (labels != -100).nonzero().squeeze()
active_loss_position = (labels != -100)
top_k = 2
top_k_preds = torch.topk(logits, k=top_k, dim=-1).indices
top_k_correct = torch.eq(top_k_preds, labels.unsqueeze(-1)).any(dim=-1).float().sum()
top_k_acc = top_k_correct / active_loss_position.size(0)
preds = torch.argmax(logits, dim=-1)
acc = (preds[active_loss_position] == labels[active_loss_position]).float().mean()  #这个True False的tensor可以直接作为index


In [18]:
print(labels.unsqueeze(-1))

tensor([[   4],
        [-100],
        [   3]])


In [15]:
print(preds[active_loss_position])

tensor([0, 4])


In [14]:
print(preds)
print(acc)

tensor([0, 4, 4])
tensor(0.)


In [11]:
print(active_loss_position)

tensor([ True, False,  True])


In [9]:
print(top_k_preds)

tensor([[0, 1],
        [4, 1],
        [4, 3]])


In [19]:
print(top_k_acc)

tensor(0.5000)


In [5]:
a = [1,2]
import torch
a = torch.tensor(a,dtype=torch.float32)

In [3]:
print(a)

tensor(1.5000)


In [6]:
print(a.item())

ValueError: only one element tensors can be converted to Python scalars